version: '3'
services:
  db:
    container_name: pgsql
    image: postgres:13.1
    environment:
      - DEBUG=false
      - POSTGRES_DB=hadb
      - POSTGRES_USER=ha
      - POSTGRES_PASSWORD=password2021dljfklkla1!kljf;
    volumes:
      - ./postgresql/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    user: 1000:1000
  webserver:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - homeassistant
  sftp:
    image: atmoz/sftp
    container_name: sftp
    volumes:
        - ./download:/home/user/upload
    ports:
        - "2222:22"
    command: user:qwlqfhkllazxcloewkrj:1000
  adminer:
    image: adminer:4.8.0
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 9000:8080
    environment:
      ADMINER_DEFAULT_SERVER: 192.168.1.112
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_NAME: hadb
#       ADMINER_PASSWORD: password2021dljfklkla1!kljf;
      ADMINER_USERNAME: ha
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    volumes:
        - ./adminer/index.php:/var/www/html/index.php
        
volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ./http/
      o: bind

#networks:
#  app-network:
#    driver: bridge
